### ISSUE TITLE
false-positive: variable dependencies in for loop

### ISSUE THREAD

**Issue by johejo** [sanposhiho/wastedassign#23]
If this is not false-positive, please close it.

```go
package main

func main() {
	var x int = 0
	var y int = 1
	for i := 1; i < 3; i++ {
		x += y
		y *= 2 * i
	}
	println(x)
}
```

```
# command-line-arguments
testdata/a.go:8:3: reassigned, but never used afterwards
```

**Comment by sanposhiho** [comment]
Hi, @johejo. Thanks for reporting!
I'll close this issue as it seems to be similar to #21 .

As [the comment of #21](https://github.com/sanposhiho/wastedassign/issues/21#issuecomment-787089610), this report is not wrong, but, wastedassign should not report this.

So, I'll fix this issue as soon as possible, thanks
