### ISSUE TITLE
SSA and generics (go1.18)

### ISSUE THREAD

**Issue by ldez** [sanposhiho/wastedassign#41]
Currently, SSA is not working with generics.

So your linter produces a panic when it is used with generics.

There is an issue open about that in the Go repository: https://github.com/golang/go/issues/48525

Inside golangci-lint, we have disabled your linters: https://github.com/golangci/golangci-lint/issues/2649

You have 2 solutions:
- waiting for a version of SSA that will support generics
- dropping the SSA analyzers and using something else to analyze the code.

Related to https://github.com/golang/go/issues/50558

**Comment by sanposhiho** [comment]
Hm, thanks for informing. wait for a new version of SSA.

**Comment by ldez** [comment]
SSA has been updated and it seems to work inside golangci-lint.

**Comment by sanposhiho** [comment]
Thanks

**Comment by ldez** [comment]
in fact, the problem is still here

**Comment by ldez** [comment]
The code of the linter needs to be adapted to manage generics:

```go
func wastedassignG[T ~int](hoge T) {
	var i int
	for {
		hoge = 5 // <- not detected KO
		// break
	}

	println(i)
	println(hoge)
	return
}

func wastedassign(hoge int) {
	var i int
	for {
		hoge = 5 // <- detected OK
		// break
	}

	println(i)
	println(hoge)
	return
}
```

**Comment by ldez** [comment]
go1.19 will come in about 2 weeks, it can be good if you can fix your linter before this release.

**Comment by migregal** [comment]
Hi, everyone!

Is there any movement about go1.19 release? Actually, i can't reproduce that problem with new version:

main.go
```go
package main

import "fmt"

func wastedassignG[T ~int](hoge T) {
	var i int
	for {
		i = 5
	}

	fmt.Println(i)
}

func wastedassign(hoge int) {
	var i int
	for {
		i = 5
	}

	fmt.Println(i)
}

func main() {

}
```

And it gives me this output:
```
$ go vet -vettool=`which wastedassign` ./main/...                                                                                          
# <path>/main
main/main.go:8:3: assigned to i, but reassigned without using the value
main/main.go:17:3: assigned to i, but reassigned without using the value
```

Seems like it was fixed and golangci-lint can reenable wastedassign?
